---
# optimizer options
optimizer: "sgd"
batch_size: 128
learning_rate: 0.05
momentum: 0.9
l2_reg: 0.0005

# lr scheduler options
lr_gamma: 0.1
lr_milestones:
  - 80
  - 100

# training options
epochs: 120
eval_every: 1

# model options
width: 16
density: 1.0
model: "resnet32"

# dataset options
dataset: "CIFAR10"
data_root: "data/"
cache: true
mislabel_ratio: 0.8
asym: False
subset: false
subset_size: 0.01
cifar_img_size: 32
webvision_img_size: 227

# elr options
elr: true
elr_lambda: 3.0
elr_beta: 0.7

# mixup options
mixup: false
mixup_strength: 1.0

# run options
gpu: 6
num_workers: 8
pin_memory: true
prefetch_factor: 4
run_name: "cifar10_debug_elr"
save_dir: "saved_debug/"

# model loading options
load_model: false
load_model_path: "saved/template_xxxxxx/final_model"
