---
# optimizer options
optimizer: "sgd"
batch_size: 32
learning_rate: 0.02
momentum: 0.9
l2_reg: 0.0005

# lr scheduler options
lr_gamma: 0.01
lr_milestones:
  - 40
  - 80

# training options
epochs: 150
eval_every: 2

# model options
width: 64
density: 1.0
model: "resnet50"

# dataset options
dataset: "webvision"
data_root: "data/"
cache: false
mislabel_ratio: 0.0
asym: False
subset: false
subset_size: 0.01
cifar_img_size: 32
webvision_img_size: 128

# elr options
elr: true
elr_lambda: 3.0
elr_beta: 0.7

# mixup options
mixup: false
mixup_strength: 1.0

# run options
gpu: 0
num_workers: 8
pin_memory: true
prefetch_factor: 2
run_name: "webvision_resnet50"
save_dir: "saved/"

# model loading options
load_model: false
load_model_path: "saved/template_xxxxxx/final_model"
